<?php

namespace App\Infrastructure\Movie;

use App\Domain\Movie\Movie;
use App\Domain\Movie\MovieRepositoryInterface;

class InMemoryMovieRepository implements MovieRepositoryInterface
{
    public function findAll(): array
    {
        return [
            new Movie("Pulp Fiction"),
            new Movie("Incepcja"),
            new Movie("Skazani na Shawshank"),
            new Movie("Dwunastu gniewnych ludzi"),
            new Movie("Ojciec chrzestny"),
            new Movie("Django"),
            new Movie("Matrix"),
            new Movie("Leon zawodowiec"),
            new Movie("Siedem"),
            new Movie("Nietykalni"),
            new Movie("Władca Pierścieni: Powrót króla"),
            new Movie("Fight Club"),
            new Movie("Forrest Gump"),
            new Movie("Chłopaki nie płaczą"),
            new Movie("Gladiator"),
            new Movie("Człowiek z blizną"),
            new Movie("Pianista"),
            new Movie("Doktor Strange"),
            new Movie("Szeregowiec Ryan"),
            new Movie("Lot nad kukułczym gniazdem"),
            new Movie("Wielki Gatsby"),
            new Movie("Avengers: Wojna bez granic"),
            new Movie("Życie jest piękne"),
            new Movie("Pożegnanie z Afryką"),
            new Movie("Szczęki"),
            new Movie("Milczenie owiec"),
            new Movie("Dzień świra"),
            new Movie("Blade Runner"),
            new Movie("Labirynt"),
            new Movie("Król Lew"),
            new Movie("La La Land"),
            new Movie("Whiplash"),
            new Movie("Wyspa tajemnic"),
            new Movie("Django"),
            new Movie("American Beauty"),
            new Movie("Szósty zmysł"),
            new Movie("Gwiezdne wojny: Nowa nadzieja"),
            new Movie("Mroczny Rycerz"),
            new Movie("Władca Pierścieni: Drużyna Pierścienia"),
            new Movie("Harry Potter i Kamień Filozoficzny"),
            new Movie("Green Mile"),
            new Movie("Iniemamocni"),
            new Movie("Shrek"),
            new Movie("Mad Max: Na drodze gniewu"),
            new Movie("Terminator 2: Dzień sądu"),
            new Movie("Piraci z Karaibów: Klątwa Czarnej Perły"),
            new Movie("Truman Show"),
            new Movie("Skazany na bluesa"),
            new Movie("Infiltracja"),
            new Movie("Gran Torino"),
            new Movie("Spotlight"),
            new Movie("Mroczna wieża"),
            new Movie("Rocky"),
            new Movie("Casino Royale"),
            new Movie("Drive"),
            new Movie("Piękny umysł"),
            new Movie("Władca Pierścieni: Dwie wieże"),
            new Movie("Zielona mila"),
            new Movie("Requiem dla snu"),
            new Movie("Forest Gump"),
            new Movie("Requiem dla snu"),
            new Movie("Milczenie owiec"),
            new Movie("Czarnobyl"),
            new Movie("Breaking Bad"),
            new Movie("Nędznicy"),
            new Movie("Seksmisja"),
            new Movie("Pachnidło"),
            new Movie("Nagi instynkt"),
            new Movie("Zjawa"),
            new Movie("Igrzyska śmierci"),
            new Movie("Kiler"),
            new Movie("Siedem dusz"),
            new Movie("Dzień świra"),
            new Movie("Upadek"),
            new Movie("Lśnienie"),
            new Movie("Pan życia i śmierci"),
            new Movie("Gladiator"),
            new Movie("Granica"),
            new Movie("Hobbit: Niezwykła podróż"),
            new Movie("Pachnidło: Historia mordercy"),
            new Movie("Wielki Gatsby"),
            new Movie("Titanic"),
            new Movie("Sin City"),
            new Movie("Przeminęło z wiatrem"),
            new Movie("Królowa śniegu"),
        ];
    }
}
